In [38]:
import pandas as pd
import numpy as np
import os

cwd = os.getcwd()
df_AUS = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='AUS CY').fillna(0)
df_NSW = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='NSW CY').fillna(0)
df_VIC = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='VIC CY').fillna(0)
df_QLD = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='QLD CY').fillna(0)
df_SA = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='SA CY').fillna(0)
df_WA = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='WA CY').fillna(0)
df_TAS = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='TAS CY').fillna(0)
df_NT = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='NT CY').fillna(0)
df_Summary = pd.read_excel(cwd + "/ausenergystat2024.xlsx", sheet_name='State summary 2023').fillna(0)

In [39]:
df_Summary

,Unnamed: 0,NSW,VIC,QLD,WA,SA,TAS,NT,AUS
0,Black coal,43360.917,0.000,42918.149,7690.248,0.000,0.000,0.000,93969.315
1,Brown coal,0.000,31640.536,0.000,0.000,0.000,0.000,0.000,31640.536
2,Natural gas,2320.984,1166.101,8889.033,26555.941,3401.780,175.555,4160.223,46669.616
3,Oil products,392.839,238.198,1245.662,2201.764,244.652,12.669,527.223,4863.007
4,Total non-renewable,46074.740,33044.835,53052.844,36447.953,3646.432,188.223,4687.446,177142.474
5,Biomass,979.110,742.503,1157.081,113.525,90.807,33.764,8.892,3125.683
6,Wind,5791.602,11884.816,2629.142,3345.461,6315.161,1901.730,0.000,31867.912
7,Hydro,3712.658,2591.162,1340.231,71.320,1.554,8258.136,0.030,15975.089
8,Large-scale solar PV,6747.892,1919.098,6248.817,931.174,1180.753,3.732,54.175,17085.640
9,Small-scale solar PV,8222.093,4973.165,7736.094,3344.520,3036.967,324.225,271.642,27908.706
10,Geothermal,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
11,Total renewable,25453.354,22110.744,19111.365,7805.999,10625.242,10521.587,334.739,95963.030
12,Total,71528.094,55155.579,72164.208,44253.953,14271.674,10709.810,5022.186,273105.504
13,Per cent renewable generation,0.356,0.401,0.265,0.176,0.744,0.982,0.067,0.351

In [40]:
import matplotlib.pyplot as plt